###############################################################################
# OpenEtruscan production dashboard.
#
# The previous version had one widget (the `heavy_endpoints` user metric).
# Useful, but useless on its own — when the API was slow you couldn't tell
# whether the symptom lived on the GCE VM, in Cloud SQL, or in one of the
# Cloud Run inference services.
#
# This version uses *only* metrics emitted by the platform (GCE, Cloud SQL,
# Cloud Run) plus the two user metrics already wired in `alerts.tf`. Nothing
# here depends on instrumentation we don't actually ship.
#
# Layout (12-column mosaic, top-to-bottom traffic-light reading order):
#
#   Row 1   API VM CPU                   |  API VM network in/out
#   Row 2   Cloud SQL CPU                |  Cloud SQL active connections
#   Row 3   Cloud Run req rate           |  Cloud Run 5xx rate
#   Row 4   Cloud Run p95 latency        |  Heavy-endpoint count (legacy)
#   Row 5   Admin-token misconfig events |  Cloud SQL slow-query rate
#
# Editing tip: `dashboard_json` is a JSON string built by `jsonencode()`.
# Use `terraform fmt` for the HCL; the JSON inside the encoded block is
# autogenerated, so don't try to hand-edit indentation.
###############################################################################

locals {
  api_instance_id_filter = "resource.label.instance_id=\"${google_compute_instance.api.instance_id}\""
  cloudsql_db_id         = "${var.project_id}:${google_sql_database_instance.main.name}"
}

resource "google_monitoring_dashboard" "api_endpoints" {
  dashboard_json = jsonencode({
    displayName = "OpenEtruscan API & Anchors"
    mosaicLayout = {
      columns = 12
      tiles = [
        # ─────────────────────────────── Row 1: API VM ──────────────────────
        {
          xPos = 0, yPos = 0, width = 6, height = 4
          widget = {
            title = "API VM — CPU utilisation"
            xyChart = {
              dataSets = [{
                timeSeriesQuery = {
                  timeSeriesFilter = {
                    filter = "metric.type=\"compute.googleapis.com/instance/cpu/utilization\" resource.type=\"gce_instance\" ${local.api_instance_id_filter}"
                    aggregation = {
                      alignmentPeriod    = "60s"
                      perSeriesAligner   = "ALIGN_MEAN"
                      crossSeriesReducer = "REDUCE_MEAN"
                    }
                  }
                }
                plotType = "LINE"
              }]
              yAxis = { label = "fraction", scale = "LINEAR" }
            }
          }
        },
        {
          xPos = 6, yPos = 0, width = 6, height = 4
          widget = {
            title = "API VM — network bytes/s (in + out)"
            xyChart = {
              dataSets = [
                {
                  timeSeriesQuery = {
                    timeSeriesFilter = {
                      filter = "metric.type=\"compute.googleapis.com/instance/network/received_bytes_count\" resource.type=\"gce_instance\" ${local.api_instance_id_filter}"
                      aggregation = {
                        alignmentPeriod  = "60s"
                        perSeriesAligner = "ALIGN_RATE"
                      }
                    }
                  }
                  plotType       = "LINE"
                  legendTemplate = "in"
                },
                {
                  timeSeriesQuery = {
                    timeSeriesFilter = {
                      filter = "metric.type=\"compute.googleapis.com/instance/network/sent_bytes_count\" resource.type=\"gce_instance\" ${local.api_instance_id_filter}"
                      aggregation = {
                        alignmentPeriod  = "60s"
                        perSeriesAligner = "ALIGN_RATE"
                      }
                    }
                  }
                  plotType       = "LINE"
                  legendTemplate = "out"
                },
              ]
              yAxis = { label = "B/s", scale = "LINEAR" }
            }
          }
        },

        # ─────────────────────────────── Row 2: Cloud SQL ───────────────────
        {
          xPos = 0, yPos = 4, width = 6, height = 4
          widget = {
            title = "Cloud SQL — CPU utilisation"
            xyChart = {
              dataSets = [{
                timeSeriesQuery = {
                  timeSeriesFilter = {
                    filter = "metric.type=\"cloudsql.googleapis.com/database/cpu/utilization\" resource.type=\"cloudsql_database\" resource.label.database_id=\"${local.cloudsql_db_id}\""
                    aggregation = {
                      alignmentPeriod  = "60s"
                      perSeriesAligner = "ALIGN_MEAN"
                    }
                  }
                }
                plotType = "LINE"
              }]
              yAxis = { label = "fraction", scale = "LINEAR" }
            }
          }
        },
        {
          xPos = 6, yPos = 4, width = 6, height = 4
          widget = {
            title = "Cloud SQL — active connections"
            xyChart = {
              dataSets = [{
                timeSeriesQuery = {
                  timeSeriesFilter = {
                    filter = "metric.type=\"cloudsql.googleapis.com/database/postgresql/num_backends\" resource.type=\"cloudsql_database\" resource.label.database_id=\"${local.cloudsql_db_id}\""
                    aggregation = {
                      alignmentPeriod  = "60s"
                      perSeriesAligner = "ALIGN_MEAN"
                    }
                  }
                }
                plotType = "LINE"
              }]
              yAxis = { label = "count", scale = "LINEAR" }
            }
          }
        },

        # ─────────────────────────────── Row 3: Cloud Run rate / errors ─────
        {
          xPos = 0, yPos = 8, width = 6, height = 4
          widget = {
            title = "Cloud Run — request rate (byt5 + minilm + iiif)"
            xyChart = {
              dataSets = [{
                timeSeriesQuery = {
                  timeSeriesFilter = {
                    filter = "metric.type=\"run.googleapis.com/request_count\" resource.type=\"cloud_run_revision\""
                    aggregation = {
                      alignmentPeriod    = "60s"
                      perSeriesAligner   = "ALIGN_RATE"
                      crossSeriesReducer = "REDUCE_SUM"
                      groupByFields      = ["resource.label.service_name"]
                    }
                  }
                }
                plotType = "LINE"
              }]
              yAxis = { label = "req/s", scale = "LINEAR" }
            }
          }
        },
        {
          xPos = 6, yPos = 8, width = 6, height = 4
          widget = {
            title = "Cloud Run — 5xx rate"
            xyChart = {
              dataSets = [{
                timeSeriesQuery = {
                  timeSeriesFilter = {
                    filter = "metric.type=\"run.googleapis.com/request_count\" resource.type=\"cloud_run_revision\" metric.label.response_code_class=\"5xx\""
                    aggregation = {
                      alignmentPeriod    = "60s"
                      perSeriesAligner   = "ALIGN_RATE"
                      crossSeriesReducer = "REDUCE_SUM"
                      groupByFields      = ["resource.label.service_name"]
                    }
                  }
                }
                plotType = "LINE"
              }]
              yAxis = { label = "5xx/s", scale = "LINEAR" }
            }
          }
        },

        # ─────────────────────────────── Row 4: latency + legacy widget ─────
        {
          xPos = 0, yPos = 12, width = 6, height = 4
          widget = {
            title = "Cloud Run — p95 request latency"
            xyChart = {
              dataSets = [{
                timeSeriesQuery = {
                  timeSeriesFilter = {
                    filter = "metric.type=\"run.googleapis.com/request_latencies\" resource.type=\"cloud_run_revision\""
                    aggregation = {
                      alignmentPeriod    = "60s"
                      perSeriesAligner   = "ALIGN_DELTA"
                      crossSeriesReducer = "REDUCE_PERCENTILE_95"
                      groupByFields      = ["resource.label.service_name"]
                    }
                  }
                }
                plotType = "LINE"
              }]
              yAxis = { label = "ms", scale = "LINEAR" }
            }
          }
        },
        {
          xPos = 6, yPos = 12, width = 6, height = 4
          widget = {
            title = "Heavy-endpoint count (user metric)"
            xyChart = {
              dataSets = [{
                timeSeriesQuery = {
                  timeSeriesFilter = {
                    filter = "metric.type=\"logging.googleapis.com/user/heavy_endpoints\" resource.type=\"gce_instance\""
                    aggregation = {
                      alignmentPeriod    = "60s"
                      perSeriesAligner   = "ALIGN_RATE"
                      crossSeriesReducer = "REDUCE_SUM"
                    }
                  }
                }
                plotType = "LINE"
              }]
              yAxis = { label = "events/s", scale = "LINEAR" }
            }
          }
        },

        # ─────────────────────────────── Row 5: security + slow-SQL ─────────
        {
          xPos = 0, yPos = 16, width = 6, height = 4
          widget = {
            title = "Admin-token misconfig events"
            xyChart = {
              dataSets = [{
                timeSeriesQuery = {
                  timeSeriesFilter = {
                    filter = "metric.type=\"logging.googleapis.com/user/${google_logging_metric.admin_token_missing.name}\""
                    aggregation = {
                      alignmentPeriod    = "60s"
                      perSeriesAligner   = "ALIGN_RATE"
                      crossSeriesReducer = "REDUCE_SUM"
                    }
                  }
                }
                plotType = "LINE"
              }]
              yAxis = { label = "events/s", scale = "LINEAR" }
            }
          }
        },
        {
          xPos = 6, yPos = 16, width = 6, height = 4
          widget = {
            title = "Cloud SQL — slow-query rate"
            xyChart = {
              dataSets = [{
                timeSeriesQuery = {
                  timeSeriesFilter = {
                    filter = "metric.type=\"cloudsql.googleapis.com/database/postgresql/transaction_count\" resource.type=\"cloudsql_database\" metric.label.transaction_type=\"slow_query\""
                    aggregation = {
                      alignmentPeriod    = "60s"
                      perSeriesAligner   = "ALIGN_RATE"
                      crossSeriesReducer = "REDUCE_SUM"
                    }
                  }
                }
                plotType = "LINE"
              }]
              yAxis = { label = "slow tx/s", scale = "LINEAR" }
            }
          }
        },
      ]
    }
  })
}
