"""initial_schema

Revision ID: 12beabe2bd09
Revises:
Create Date: 2026-04-04 12:28:05.199232

History note (2026-07-17)
-------------------------
As originally committed this migration was an empty stamp: it was
autogenerated against the then-live production database, whose schema
already existed, so ``upgrade()`` was ``pass``. That made the whole chain
un-bootstrappable — ``alembic upgrade head`` on an empty database failed at
the second migration because ``inscriptions`` never got created (caught by
``tests/test_migrations.py``).

The DDL below is the reconstructed 2026-04-04 base schema: the two tables
that every later migration builds on (``inscriptions``,
``genetic_samples``), WITHOUT anything the later chain adds itself —
``source_code``/``source_detail``/``original_script_entry`` (b2e3d4f5a6b7),
``source_id`` + FK (c3f4d5e6a7b8), ``zotero_id`` (f1a2b3c4d5e6),
``fts_canonical`` (e7c8d9e0f1a2), the five archaeogenetics columns
(a6d56926ff21, g2b3c4d5e6f7), and all later-created tables.
``provenance_status`` defaults to ``'verified'`` here because that was the
pre-a1f2c3d4e5f6 state that migration's backfill narrative documents.

Databases that were stamped with the original empty revision are
unaffected: this ``upgrade()`` only ever runs on fresh databases.
"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "12beabe2bd09"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the 2026-04-04 base schema on an empty database."""
    op.execute(
        """
        CREATE TABLE inscriptions (
            id TEXT NOT NULL,
            canonical TEXT NOT NULL,
            phonetic TEXT NOT NULL,
            old_italic TEXT NOT NULL,
            raw_text TEXT NOT NULL,
            canonical_clean TEXT,
            old_italic_v2 TEXT,
            data_quality TEXT,
            translation TEXT,
            canonical_words_only TEXT,
            year_from INTEGER,
            year_to INTEGER,
            intact_token_ratio FLOAT,
            findspot TEXT,
            findspot_lat FLOAT,
            findspot_lon FLOAT,
            findspot_uncertainty_m FLOAT,
            date_approx INTEGER,
            date_uncertainty INTEGER,
            medium TEXT,
            object_type TEXT,
            source TEXT,
            bibliography TEXT,
            notes TEXT,
            language TEXT NOT NULL,
            classification TEXT NOT NULL,
            script_system TEXT NOT NULL,
            completeness TEXT NOT NULL,
            provenance_status TEXT DEFAULT 'verified' NOT NULL,
            provenance_flags TEXT NOT NULL,
            trismegistos_id TEXT,
            eagle_id TEXT,
            pleiades_id TEXT,
            geonames_id TEXT,
            is_codex BOOLEAN NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
            CONSTRAINT pk_inscriptions PRIMARY KEY (id)
        )
        """
    )
    op.execute("CREATE INDEX ix_inscriptions_findspot ON inscriptions (findspot)")
    op.execute("CREATE INDEX ix_inscriptions_date_approx ON inscriptions (date_approx)")
    op.execute("CREATE INDEX ix_inscriptions_language ON inscriptions (language)")
    op.execute("CREATE INDEX ix_inscriptions_classification ON inscriptions (classification)")
    op.execute("CREATE INDEX ix_inscriptions_canonical ON inscriptions (canonical)")

    op.execute(
        """
        CREATE TABLE genetic_samples (
            id TEXT NOT NULL,
            findspot TEXT,
            findspot_lat FLOAT,
            findspot_lon FLOAT,
            findspot_uncertainty_m FLOAT,
            date_approx INTEGER,
            date_uncertainty INTEGER,
            y_haplogroup TEXT,
            mt_haplogroup TEXT,
            source TEXT,
            notes TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
            CONSTRAINT pk_genetic_samples PRIMARY KEY (id)
        )
        """
    )
    op.execute("CREATE INDEX ix_genetic_samples_date_approx ON genetic_samples (date_approx)")


def downgrade() -> None:
    """Drop the base schema."""
    op.execute("DROP TABLE IF EXISTS genetic_samples")
    op.execute("DROP TABLE IF EXISTS inscriptions")
